### ISSUE TITLE
Tinder Roommates (Roommate Matching & Reviews)

### ISSUE THREAD

**Issue by WilliamOdumah** [WilliamOdumah/RoomHub#31]
### Description:
The Tinder Roommates feature allows users to review current roommates and connect with new potential roommates. Users can send and receive connection requests and review profiles before making connections.

### User Stories:
- [ ] #31 As a user, I should be able to review my current roommates.
- [ ] #32 As a user, I should be able to find new potential roommates.
- [ ] #33 As a user, I should be able to send a connection request to a potential roommate.
- [ ] #34 As a user, I should be able to receive and accept/reject connection requests from potential roommates.
- [ ] #35 As a user, I should be able to view information about roommates who have accepted my connection request.
- [ ] #37 As a user, I should be able to view reviews of potential roommates before connecting.
- [ ] #38 As a user, I should receive a notification when a potential roommate sends me a connection request.
